name: chemsearch
channels:
  - conda-forge
  - defaults
  - rdkit
dependencies:
  - pip
  - python=3
  - flask
  - flask-wtf
  - rdkit
  - pandas
  - oauth2client
  - openbabel
  - python-dotenv
  - google-api-python-client
  - google-auth
  - google-auth-httplib2
  - gunicorn
  - flask-bootstrap
  - matplotlib
  - Flask-Login
  - Flask-SQLAlchemy
  - rauth
  - Flask-Moment
  - beautifulsoup4
  - markdown
  - bleach
  - pyyaml
  - gevent
  - pip:
    - gspread
    - pyscaffold
    - flask-shell-ipython
    - flask-migrate
    - more-itertools
# NON-ESSENTIAL
#  - jupyter
#  - jupyterlab
#  - jupyter_contrib_nbextensions
#  - pip:
#    - Flask-Session
